# Generated by Django 5.1.1 on 2024-09-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_customer_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='unavailable_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
